
== Introduction

Kubernetes has become the container orchestration standard. Most cloud and virtualization vendors now offer it as standard infrastructure. {portfolioName} users have the choice of creating Kubernetes clusters with Rancher Kubernetes Engine (RKE), lightweight edge-centric K3s, on premise or in cloud Kubernetes services, such as GKE, AKS, and EKS. {prodName} users can also import and manage their existing Kubernetes clusters created using any Kubernetes distribution or installer.

=== Background

Even on the journey to a full https://landscape.cncf.io/[Cloud Native Landscape], classic IT pillars are still valid considerations. General requirements include the need for a small, purpose-built operating system with a container runtime engine and a container orchestration platform to distribute workloads across a target, clustered instance. The dominant technology for container orchestration is Kubernetes. With its large community of developers and a plethora of features and capabilities, Kubernetes has become the defacto standard and is included across most container-as-a-service platforms. With all of these attributes in place, both developer and operation teams can effectively deploy, manage and deliver functionality to their end users in a resilient and agile manner.

NOTE: As a further reference, the National Institute of Standards and Technology's (NIST) https://csrc.nist.gov/publications/detail/sp/800-180/draft[Definition of Microservices, Application Containers and System Virtual Machines] describes the important characteristics of application containers.

=== Motivation

ifdef::pnRancher[]
While any developer or organization may simply start with a single, Kubernetes-based deployment, it is very common for that number of cluster instances to rapidly grow. While each of these may have specific focus areas, it becomes imperative to figure out how to use, manage, maintain and replicate the all of these instances over time. This is where {prodName} leads the industry, being able to manage access, usage, infrastructure and applications across clusters, that are ( https://www.cncf.io/certification/software-conformance/[CNCF] ) compliant, anywhere from edge, core, on-premise, or cloud.
endif::pnRancher[]

=== Scope

ifdef::pnRancher[]
The scope of this document is to provide a quick-start, reference implementation of {prodName}. This can be done in a variety of solution stack, architectural scenarios as a fundamental component of an overall Kubernetes ecosystem.
endif::pnRancher[]


=== Audience

This document is intended for IT decision makers, architects, system administrators and technicians who are implementing a flexible, software-defined Kubernetes management platform. You should be familiar with the traditional IT infrastructure pillars -- networking, computing and storage -- along with the local use cases for sizing, scaling and limitations within each pillars' environments.

////

Reference Architecture

Description of the reference architecture/Solution Name and the partners included in the design and validation.  Provided as a proof point for designing similar production ready solutions with design considerations, implementation suggestion, and best practices.  May include statement regarding consulting, technical support and the intended audiences.
////

////

Enterprise Architecture

Beyond the general introduction/overview, in each of following chapters, content includes how this layer provides the necessary attributes to the one above, details and context for this layer itself, and what requirements are needed by the underlying layer. Thus readers are encouraged to scan the entire document to understand the overall solution, even if only expexpected to focus on a certain layer's aspect.

////

