ifdef::RA,RC,RI,GS[]

== Introduction

On the digital transformation journey to a full Cloud Native Landscape, utilization of microservices becomes the main approach with the dominant technology for such container orchestration being Kubernetes footnote:[https://kubernetes.io/]
With its large community of developers and abundant features and capabilities, Kubernetes has become the defacto standard and is included across most container-as-a-service platforms.  With all of these technologies in place, both developer and operation teams can effectively deploy, manage and deliver functionality to their end users in a resilient and agile manner.

=== Motivation

ifeval::["{focus}" == "{an_Rancher}"]
While any developer or organization may simply start with a single, Kubernetes-based deployment, it is very common for that number of cluster instances to rapidly grow. While each of these may have specific focus areas, it becomes imperative to figure out how to use, manage, maintain and replicate the all of these instances over time.

This is where {pn_Rancher} leads the industry, being able to manage access, usage, infrastructure and applications across clusters, that are Cloud Native Computing Foundation ( CNCF footnote:[https://www.cncf.io/certification/software-conformance] ) compliant, anywhere across edge, on-premise data centers, or cloud service providers.  {pn_Rancher} optimizes creating and managing Kubernetes clusters like:

* {pn_RKE1} ( {pn_RKE1_ProductPage}[{an_RKE1}] )
// * {pn_RKE2} ( {pn_RKE2_ProductPage}[{an_RKE2}] ) and
* Lightweight edge-centric {pn_K3s_ProductPage}[{pn_K3s}]
* other Kubernetes clusters that are based upon CNCF footnote:[https://www.cncf.io/] certified footnote:[https://www.cncf.io/certification/cka/] Kubernetes distributions or installers

and deployed across various supported footnote:[{pn_Rancher_SupportPage}] infrastructure elements.

ifdef::RC[]
Once on the digital transformation journey with {pn_Rancher}, some of the next focus areas are:

ifdef::iISV[]
* Workloads
** Determine how to launch either internally developed containerized, microservice workloads or leverage offerings from Independent Software Vendors ( ISV ).
endif::iISV[]

ifdef::iCSP,iIHV[]
* Compute Platform
** To optimize availability, performance, scalability and integrity, assess current system platforms or acquire and utilize new variations from:
ifdef::iIHV[]
*** Independent Hardware Vendors ( IHV ) for physical, baremetal, hypervisors and virtual machines
endif::iIHV[]
ifdef::iCSP[]
*** Cloud Service Providers ( CSP ), which can also include baremetal, virtual machines plus hosted Kubernetes services
endif::iCSP[]
endif::iCSP,iIHV[]

endif::RC[]

endif::[]

ifeval::["{focus}" == "{an_RKE1}"]
FixMe- While any developer or organization may simply start with a single, Kubernetes-based deployment, it is very common for that number of cluster instances to rapidly grow. While each of these may have specific focus areas, it becomes imperative to figure out how to use, manage, maintain and replicate the all of these instances over time.

FixMe- This is where {pn_Rancher} leads the industry, being able to manage access, usage, infrastructure and applications across clusters, that are Cloud Native Computing Foundation ( CNCF footnote:[https://www.cncf.io/certification/software-conformance] ) compliant, anywhere across edge, on-premise data centers, or cloud service providers.  {pn_Rancher} optimizes creating and managing Kubernetes clusters like:

* {pn_RKE1} ( {pn_RKE1_ProductPage}[{an_RKE1}] )
// * {pn_RKE2} ( {pn_RKE2_ProductPage}[{an_RKE2}] ) and
* Lightweight edge-centric {pn_K3s_ProductPage}[{pn_K3s}]
* other Kubernetes clusters that are based upon CNCF footnote:[https://www.cncf.io/] certified footnote:[https://www.cncf.io/certification/cka/] Kubernetes distributions or installers

FixMe- and deployed across various supported footnote:[{pn_Rancher_SupportPage}] infrastructure elements.

ifdef::RC[]
FixMe- Once on the digital transformation journey with {pn_Rancher}, some of the next focus areas are:

ifdef::iISV[]
* Workloads
** Determine how to launch either internally developed containerized, microservice workloads or leverage offerings from Independent Software Vendors ( ISV ).
endif::iISV[]

ifdef::iCSP,iIHV[]
* Compute Platform
** To optimize availability, performance, scalability and integrity, assess current system platforms or acquire and utilize new variations from:
ifdef::iIHV[]
*** Independent Hardware Vendors ( IHV ) for physical, baremetal, hypervisors and virtual machines
endif::iIHV[]
ifdef::iCSP[]
*** Cloud Service Providers ( CSP ), which can also include baremetal, virtual machines plus hosted Kubernetes services
endif::iCSP[]
endif::iCSP,iIHV[]

endif::RC[]

endif::[]

=== Scope

The scope of this document is to provide a
ifndef::RA[]
complete
ifdef::EA[<<G_EA,enterprise architecture>>]
ifdef::SS[<<G_EA,solution stack>>]
including
endif::RA[]
ifndef::RC,RI,GS[]
detailed
ifdef::RA[<<G_RA,reference architecture>>]
for
endif::RC,RI,GS[]
ifndef::RI,GS[]
layered
ifdef::RA+RC[<<G_RC,reference configuration>>]
for
endif::RI,GS[]
ifndef::RC,GS[]
general
ifdef::RA+RI[<<G_RI,reference implementation>>]
of
endif::RC,GS[]
ifndef::RC,RI[]
simplified,
ifdef::RA+GS[<<G_GS,getting started>>]
approach for
endif::RC,RI[]
ifeval::["{focus}" == "{an_Rancher}"]
{pn_Rancher}. This can be done in a variety of solution stack, architectural scenarios as a fundamental component of a managing multiple Kubernetes ecosystems.
endif::[]
ifeval::["{focus}" == "{an_RKE1}"]
{pn_RKE1}.
This can be done in a variety of scenarios to create an enterprise Kubernetes cluster deployment.
endif::[]

=== Audience

This document is intended for IT decision makers, architects, system administrators and technicians who are implementing a flexible, software-defined Kubernetes management platform. You should be familiar with the traditional IT infrastructure pillars -- networking, computing and storage -- along with the local use cases for sizing, scaling and limitations within each pillars' environments.

endif::RA,RC,RI,GS[]

////

Reference Architecture

Description of the reference architecture/Solution Name and the partners included in the design and validation.  Provided as a proof point for designing similar production ready solutions with design considerations, implementation suggestion, and best practices.  May include statement regarding consulting, technical support and the intended audiences.
////

////

Enterprise Architecture

Beyond the general introduction/overview, in each of following chapters, content includes how this layer provides the necessary attributes to the one above, details and context for this layer itself, and what requirements are needed by the underlying layer. Thus readers are encouraged to scan the entire document to understand the overall solution, even if only expexpected to focus on a certain layer's aspect.

////

