include::../SUSE/RKE1/SA_vars.adoc


ifdef::focusRKE1,layerRKE1[]
=== {pn_RKE1}

// leverage multiple prep sections
ifdef::layerSLEMicro,layerSLES[include::./SA-RA-Deployment-OS-prep.adoc[]]
ifdef::focusRancher[]
+
. Identify the appropriate, supported version of the {pn_RKE1} binary (e.g. vX.Y.Z), by reviewing the "{portfolioName} Support Matrix" on the {pn_Rancher_SupURL}[Support and Maintenance Terms of Service] web page. 
endif::focusRancher[]
ifndef::focusRancher[]
+
. Identify the appropriate, desired version of the {pn_RKE1} binary (e.g. vX.Y.Z), by reviewing the "Releases" on the {pn_K3s_Download}[Download] web page. 
endif::focusRancher[]

//-
Deployment Process::

NOTE: Installing {pn_RKE1} requires a client system (i.e. admin workstation) that has been configured with kubectl.

The primary steps for deploying this {pn_RKE1} Kubernetes
ifdef::focusRKE1[instance]
ifdef::layerRKE1[]
are:
// To meet the {pn_Rancher} prerequisites and requirements on supported Kubernetes instances,
// ifdef::layerRKE1[{pn_RKE1_ProductPage}[{pn_RKE1}]]
// can be utilized, and as desired later scaled out to a production cluster.
+
. Download the {pn_RKE1} binary according to the instructions on this webpage: https://rancher.com/docs/rke/latest/en/installation/. Continue following the directions on that website but stop before "Deploying Kubernetes with RKE".

NOTE: When creating the cluster.yml file with the command `rke config`, configure one, three, or five nodes and give them the roles of "Control Plane", "Worker", and "etcd".

. If a load balancer has been deployed for the {pn_RKE1} control-plane nodes, update the cluster.yml file (created with the command `rke config`) before deploying RKE to include the IP address or FQDN of the load balancer. The appropriate location is under authentication.sans. For example:
----
authentication:
  strategy: x509
  sans: ["rancher.susealliances.com"]
----

ifdef::layerSLEMicro[]

. Update the cluster.yml file to work with the {pn_SLEMicro} read-only fileystem as shown below:

* Update the network.options block:
----
network:
  plugin: canal
  options: {
   canal_flex_volume_plugin_dir: /opt/kubernetes/kubelet-plugins/volume/exec/nodeagent~uds,
   flannel_backend_type: vxlan 
  }
----

* Update the service.kube-controller.extra_args blocks:
----
kube-controller:
    image: ""
    extra_args: {flex-volume-plugin-dir: /opt/kubernetes/kubelet-plugins/volume/exec/}
----

endif::layerSLEMicro[]

* Refer to https://rancher.com/docs/rke/latest/en/installation/ for any additional options needed for this cluster
* When ready, run `rke up` to create the RKE cluster 

* After the `rke up` command completes the RKE cluster will continue to create Kubernetes as part of the installation process.
* Monitor the progress of the installation:
** Export the variable KUBECONFIG to the absolute pathname of the kube_config_cluster.yml file. I.e. `export KUBECONFIG=~/rke-cluster/kube_config_cluster.yml`
** Run the command: `watch -c "kubectl get deployments -A"`
*** The cluster deployment is complete when elements of all the deployments show at least "1" as "AVAILABLE"
*** Use Ctrl+c to exit the watch loop after all deployment pods are running
+

ifdef::BP[]
TIP: To address <<G_Availability>> and possible <<G_Scaling>> to a multiple node cluster, Etcd is enabled instead of using the default SQLite datastore.
+
endif::BP[]

ifdef::BP[]
//-
Deployment Consideration(s)::
To further optimize deployment factors, leverage the following practices:
ifdef::FCTR+Availability[]
* <<G_Availability>>
** While a single {pn_RKE1} node works perfectly fine, a full high-availability {pn_RKE1} cluster is recommended for production workloads. The Etcd key/value store (aka database) requires an odd number of nodes be allocated to the {pn_RKE1} etcd nodes. In this case, two additional etcd nodes should be added; for a total of three.
+
+
ifdef::focusRancher[]
In this configuration the {pn_RKE1} nodes are acting as control-plane, etcd, and worker nodes. This is perfect for the {pn_Rancher} server cluster as it does not require additional nodes to maintain a highly available {pn_Rancher} server application.
+
endif::focusRancher[]
+
endif::FCTR+Availability[]
endif::BP[]

// endif::iRancher[]

ifdef::focusRKE1[]
// Next Steps::
After this successful deployment of the {pn_RKE1} solution, review the {pn_RKE1_DocURL}[product documentation] for details on how to directly utilize this Kubernetes cluster. Furthermore, by reviewing the {pn_Rancher} {pn_Rancher_DocURL}[product documentation] this solution can also be:

* imported ( refer to sub-section "Importing Existing Clusters" ), then
* managed ( refer to sub-section "Cluster Administration" ) and
* accessed ( refer to sub-section "Cluster Access" ) to address orchestration of workloads, maintaining security and many more functions are readily available.
endif::focusRKE1[]

endif::focusK3s,layerK3s[]

