
ifdef::iK3s,iRKE1,iRKE2[]

==== Kubernetes Deployment

ifdef::iK3s[]

ifdef::iRancher[]
For this deployment, a single server installed with the {pn_SLEMicro} immutable operating system will support a single instance of {pn_K3s}. For maximum flexibility, {pn_K3s} will be deployed in a manner that would allow expanding the single-node cluster into a highly available, three-node Kubernetes cluster at a later date. 

While it is highly recommended that Kubernetes workloads (in this case the {pn_Rancher} ) be isolated from the Kubernetes control-plane and data-plane; this design will maintain all functions, including the {pn_Rancher}, on this server node. In this specialized case, the {pn_Rancher} workload is a known quantity and no other workloads will be run on this Kubernetes cluster. For this reason the {pn_Rancher} cluster is more closely aligned with appliance model best practices.

//-
Deployment Process::
The primary steps for deploying this single node {pn_K3s} cluster are:

. (Optional) Provide the server with one extra IP address that will be used as the primary address for accessing the {pn_K3s} cluster API server. This will allow the cluster to scale beyond a single server node. It is not needed if there will be an external load balancer used to access the cluster, or if the cluster will never be expanded beyond a single server node.
+
* If needed, use the `ip a` command to determine the interface name (i.e. eth0) and CIDR netmask notation (i.e. /24) of the network interface that will be configured with the extra IP address
+
* Set the following variable with the IP address and CIDR notation that will be used to access the Kubernetes API server:
+
----
SECOND_IP=""
----
+
** e.g., `SECOND_IP="10.111.2.100/24"`
+
NOTE: If the target interface is not eth0, substitute the name of the interface in place of "eth0" in the commands below.
+
----
sudo cp -np /etc/sysconfig/network/ifcfg-eth0 ~/ifcfg-eth0.`date +"%d.%b.%Y.%H.%M"`
cp -p ~/ifcfg-eth0.`date +"%d.%b.%Y"`* ~/ifcfg-eth0
echo "IPADDR_2=${SECOND_IP}" >> ~/ifcfg-eth0
diff /etc/sysconfig/network/ifcfg-eth0 ~/ifcfg-eth0
----
+
** Ensure the only difference between the original ifcfg-eth0 file and the updated ~/ifcfg-eth0 is the extra "IPADDR_2" line, then run the following commands:
+
----
sudo mv ~/ifcfg-eth0 /etc/sysconfig/network/ifcfg-eth0
sudo systemctl restart network.service
ip a
----
+
** The original server IP address and the additional IP address should be shown with the correct CIDR notation
+
. Find the appropriate version of the {pn_K3s} binary
* At the time of writing, the most current, supported version of {pn_K3s} for {pn_Rancher} is v1.20.4+k3s1. Verify the supported versions at: https://rancher.com/support-maintenance-terms/, under the "Rancher Support Matrix"
* Set the following variable with the desired version of {pn_K3s}
+
----
K3s_VERSION=""
----
+
** e.g., `K3s_VERSION="v1.20.4+k3s1"`
+
. Install {pn_K3s} with embedded etcd enabled:
+
----
curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION=${K3s_VERSION} INSTALL_K3S_EXEC='server --cluster-init --write-kubeconfig-mode=644' sh -s -
----
+
* Monitor the progress of the installation: `watch -c "kubectl get deployments -A"`
** The deployment is complete when all deployments (coredns, local-path-provisioner, metrics-server, and traefik) show at least "1" as "AVAILABLE"
*** Use Ctrl+c to exit the watch loop after all pods are running

////
Procedure for adding servers. FIRST_SERVER_IP should be the extra IP, if configured, of the first K3s server
----
FIRST_SERVER_IP=""
sudo K3S_TOKEN=<from the /var/lib/rancher/k3s/server/node-token file on the first server> INSTALL_K3S_SKIP_DOWNLOAD=true INSTALL_K3S_EXEC='server --server https://${FIRST_SERVER_IP}:6443 --write-kubeconfig-mode=644'  ./install.sh
----
////

endif::iRancher[]

endif::iK3s[]

endif::iK3s,iRKE1,iRKE2[]

