==== Operating System Deployment

ifdef::iRancher[]

include::../SUSE/SLE-Micro/SA_vars.adoc[]
include::../SUSE/Manager/SA_vars.adoc[]
include::../SUSE/RMT/SA_vars.adoc[]

On each compute platform node, install the noted {companyName} operating system.  Plan on leveraging and utilizing the following core infrastructure components and services:

* Domain Name Service (DNS) - an external network-accessible service to map IP Addresses to hostnames
* Network Time Protocol (NTP) - an external network-accessible service to obtain and synchronize system times to aid in timestamp consistency
* Software Update Service - access to a network-based repository for software update packages. This can be accessed directly from each node via registration to
** the general, internet-based {suseSCCPage}[{companyName} Customer Center] ( SCC ) or
** an organization's {pn_SUMa_ProductPage}[{pn_SUMa}] or
** a local server running an instance of {pn_RMT_DocURL}[{pn_RMT}] ( {an_RMT} )
+
NOTE: During the installation, the node can be pointed to the respective update service. This can also be accomplished post-installation with the command-line tool, {pn_SLEMicro_InstallationDocURL}[SUSEConnect].


//-
Deployment Process::
Follow these steps
* Download the {pn_SLEMicro_Download}[{pn_SLEMicro}] product (either for the ISO or Virtual Machine image)
* The installation process is described and can be performed with default values aside from your local network addressing, per the product documentation. Simply follow:
** the {pn_SLEMicro_InstallationDocURL}[Installation Quick Start] for
*** manual installation
*** raw image deployment
** or {pn_SLEMicro_AutoYaSTDocURL}[AutoYaST Guide] for unatttended installations
+
TIP: An additional consideration is, for the first node deployed, to create an additional IP address on the host network interface card. This can be used for the {pn_Rancher} access, which may also become managed by a load-balancer if a multi-node cluster becomes the base.

endif::iRancher[]

