
== Component model

ifdef::iRancher[]
This section describes the various components being used to create the {pn_Rancher}, which enables the management of multiple Kubernetes clusters, as shown in the following figure:

image::rancher-architecture-cluster-controller.svg[title="Kubernetes cluster management by {pn_Rancher}", scaledwidth=80%]
endif::iRancher[]

=== Component overview

include::../SUSE/SA.adoc[]

By utilizing these software products from the {companyName} portfolio:

ifdef::iRancher[]
* Multi-cluster Management Server - {pn_Rancher}
endif::iRancher[]
ifdef::iK3s[]
* Kubernetes Platform - {pn_K3s}
endif::iK3s[]
ifdef::iSLEMicro[]
* Operating System - {pn_SLEMicro}
endif::iSLEMicro[]

one can build the necessary infrastructure and services to administer and manage multiple Kubernetes clusters. Further details of these {companyName} products are described in the following section.

////

Provide brief descriptions of the components that make up a solution and this could include the individual components of a solution such as a product breakdown
	SUSE Linux Enterprise Server
	Docker
	Kubernetes
Or functional components that make up the solution such as Nova, Keystone, Swift, etc in an OpenStack solution 

////

ifdef::SWComp[]

ifdef::iRancher[]
==== Software - {pn_Rancher}

include::../SUSE/Rancher/SA.adoc[]

As {pn_Rancher} relies upon being deployed on a Kubernetes platform, the next section describes such a suggested component layer.

endif::iRancher[]

ifdef::iK3s[]
==== Software - {pn_K3s}

include::../SUSE/K3s/SA.adoc[]

Given that {pn_K3s} relies upon being deployed on a Linux operating system, the next section describes that target component layer.

endif::iK3s[]

ifdef::iSLEMicro[]
==== Software - {pn_SLEMicro}

include::../SUSE/SLE-Micro/SA.adoc[]

With the flexibility of {pn_SLEMicro}, multiple compute platform variants can be considered, as outlined in the next section.

endif::iSLEMicro[]

////
Depending on the number and complexity of the components this proceeding section might better be represented as a table with brief descriptions.   Fewer components can be expressed in short paragraph form.
////

////

===== FixMe - Component relationship (if necessary)

FixMe - Varius sit amet mattis vulputate. Nisi scelerisque eu ultrices vitae auctor eu augue ut ...
////

endif::SWComp[]

ifdef::HWComp[]

==== Compute Platform Options

Leveraging the enterprise grade functionality of the operating system mentioned in the previous section, many compute platforms can be the foundation of the deployment:

* Virtual machines on supported hypervisors or hosted on cloud service providers
* Physical, baremetal or single-board computers, either on-premise or hosted by cloud service providers

include::../SUSE/YES.adoc[]

NOTE: A sample bill of materials, in the <<Appendix>>, cites the necessary quantites of all components, along with a reference to the minimum resource requirements needed by the software components.

////
Provide a description of the Systems used and their position in the solution.  Each system should explain why the characteristics of that system is a good fit for the SW Component or architecture.
////

////
===== FixMe - Component relationship (if necessary)

FixMe - Varius sit amet mattis vulputate. Nisi scelerisque eu ultrices vitae auctor eu augue ut ...

////

endif::HWComp[]
