
== Component model

ifdef::iRancher[]

This section describes the various components being used to create a {pn_Rancher} deployment, in the perspective of top to bottom ordering. Once completed, the {pn_Rancher} instance enables the management of multiple Kubernetes clusters, as shown in the following figure:

// ifdef::RC,RI[]
// image::rancher-architecture-cluster-controller.svg[title="FixMe - Kubernetes cluster management by {pn_Rancher}", scaledwidth=80%]
// endif::RC,RI[]

endif::iRancher[]

=== Component overview

By utilizing:

ifdef::RC,RI,QS[]

ifdef::iRancher[]
* Multi-cluster Management Server - {pn_Rancher}
endif::iRancher[]

ifndef::QS[]
ifdef::iK3s[]
* Kubernetes Platform - {pn_K3s}
endif::iK3s[]
// ifdef::iRKE1[]
// * Kubernetes Platform - {pn_RKE1}
// endif::iRKE1[]
// ifdef::iSLES[]
// * Operating System - {pn_SLES}
// endif::iSLES[]
ifdef::iSLEMicro[]
* Operating System - {pn_SLEMicro}
endif::iSLEMicro[]
* Compute Platform
endif::QS[]
endif::RC,RI,QS[]

one can create the necessary infrastructure and services to administer and manage multiple Kubernetes clusters. Further details for these components are described in the following sections.

////

Provide brief descriptions of the components that make up a solution and this could include the individual components of a solution such as a product breakdown
	SUSE Linux Enterprise Server
	Docker
	Kubernetes
Or functional components that make up the solution such as Nova, Keystone, Swift, etc in an OpenStack solution 

////

ifdef::SWComp[]

ifdef::iRancher[]
==== Software - {pn_Rancher}

include::../SUSE/Rancher/SA.adoc[]

ifdef::RC,RI[]
As {pn_Rancher} relies upon being deployed on a Kubernetes platform, the next section describes such a suggested component layer.
endif::RC,RI[]
ifdef::QS[]
As {pn_Rancher} can be deployed on a single node, only some prerequisites for the underlying operating system are needed and will be detailed in the deployment section.
endif::QS[]

endif::iRancher[]

ifndef::QS[]

ifdef::iK3s[]
==== Software - {pn_K3s}

include::../SUSE/K3s/SA.adoc[]

Given that {pn_K3s} relies upon being deployed on a Linux operating system, the next section describes that target component layer.

endif::iK3s[]

ifdef::iSLEMicro[]
==== Software - {pn_SLEMicro}

include::../SUSE/SLE-Micro/SA.adoc[]

With the flexibility of {pn_SLEMicro}, multiple compute platform variants can be considered, as outlined in the next section.

endif::iSLEMicro[]

////
Depending on the number and complexity of the components this proceeding section might better be represented as a table with brief descriptions.   Fewer components can be expressed in short paragraph form.
////

////

===== FixMe - Component relationship (if necessary)

FixMe - Varius sit amet mattis vulputate. Nisi scelerisque eu ultrices vitae auctor eu augue ut ...
////

endif::QS[]
endif::SWComp[]

ifdef::HWComp[]
ifndef::QS[]

==== Compute Platform Options

Leveraging the enterprise grade functionality of the operating system mentioned in the previous section, many compute platforms can be the foundation of the deployment:

ifndef::iIHV[]
* Virtual machines on supported hypervisors or hosted on cloud service providers
* Physical, baremetal or single-board computers, either on-premise or hosted by cloud service providers

include::../SUSE/YES.adoc[]
endif::iIHV[]

ifdef::RC[]
ifdef::iIHV[]
ifdef::IHV-HPE[include::../IHV/HPE/SA-RA-CompMod.adoc[]]
endif::iIHV[]

// ifdef::iCSP[]
// FixMe - CSP
// endif::iCSP[]

NOTE: A sample bill of materials, in the <<Appendix>>, cites the necessary quantites of all components, along with a reference to the minimum resource requirements needed by the software components.
endif::RC[]

////
Provide a description of the Systems used and their position in the solution.  Each system should explain why the characteristics of that system is a good fit for the SW Component or architecture.
////

endif::QS[]
endif::HWComp[]

////
===== FixMe - Component relationship (if necessary)

FixMe - Varius sit amet mattis vulputate. Nisi scelerisque eu ultrices vitae auctor eu augue ut ...

////


