[preface]
== Preface

ifdef::RA,RC,RI,GS[]

The purpose of this document is to provide an overview and procedure of implementing {suseHomePage}[{companyName}] (R)
ifdef::iCSP,iIHV,iISV[and partner]
offerings for
ifeval::["{focus}" == "{an_Rancher"]
{pn_Rancher_ProductPage}[{pn_Rancher}], as a multi-cluster container management platform for organizations that deploy containerized workloads, orchestrated by Kubernetes. {pn_Rancher} makes it easy to deploy, manage, and use Kubernetes everywhere, meet IT requirements, and empower DevOps teams.
endif::[]
ifeval::["{focus}" == "{an_RKE1}"]
{pn_RKE1_ProductPage}[{pn_RKE1}] ( {an_RKE1} ), a Kubernetes distribution that runs entirely within containers on bare-metal and virtualized nodes. {an_RKE1} solves the problem of installation complexity and the operation is both simplified and easily automated, while entirely accommodating the operating system and platform it is running on.
endif::[]
ifeval::["{focus}" == "{an_RKE2}"]
pn_RKE2_ProductPage}[{pn_RKE2}] ( {an_RKE2} ), a Kubernetes distribution that runs entirely within containers on bare-metal and virtualized nodes. {an_RKE2} solves the problem of installation complexity and the operation is both simplified and easily automated, while entirely accommodating the operating system and platform it is running on. Also being a hardened, FIPS-enabled version, it adopts a compliance-based approach towards security, targeting standard risk management frameworks and best practices with the goal of stronger defense for cloud-native apps.
endif::[]
ifeval::["{focus}" == "{an_K3s}"]
pn_K3s_ProductPage}[{pn_K3s}] is an official CNCF sandbox project that delivers a lightweight yet powerful certified Kubernetes distribution designed for production workloads across resource-restrained, remote locations or on IoT devices.
endif::[]

endif::RA,RC,RI,GS[]

ifdef::EA[]
include::./SA-EA-Preface.adoc[]
endif::EA[]

