== Summary

Using components and offerings from {companyName} and the {portfolioName} portfolio streamlines your ability to quickly and effectively engage in a digital transformation, taking advantage of cloud native resources and disciplines. Using such technology approaches lets you deploy and leverage transformations of your infrastructure into a durable, reliable enterprise-grade environment.

Simplify::
Simplify and optimize your existing IT environments

ifdef::iRancher[]
* Using {pn_Rancher} enables you to simplify Kubernetes cluster management and the infrastructure components.
endif::iRancher[]

Modernize::
Bring applications and data into modern computing

ifdef::iRancher[]
* With {pn_Rancher}, the digital transformation to containerized applications can benefit from the ability both to manage many target clusters, for each of the respective user bases and to facilitate the actual workload deployments.
endif::iRancher[]

Accelerate::
Accelerate business transformation through the power of open source software

ifdef::iRancher[]
* Given the open source nature of {pn_Rancher} and the underlying softwware components, you can simplify management and make significant IT savings as you scale orchestrated, microservice deployments anywhere you need to and for whatever use cases are needed in an agile and innovative way.
endif::iRancher[]

