== Summary

Using components and offerings from {companyName} and the {portfolioName} portfolio streamlines your ability to quickly and effectively engage in a digital transformation, taking advantage of cloud native resources and disciplines. Using such technology approaches lets you deploy and leverage transformations of your infrastructure into a durable, reliable enterprise-grade environment.

Simplify::
Simplify and optimize your existing IT environments

ifdef::iRancher[]
* FixMe - Using {pn_Rancher} enables you to simplify management and make significant IT savings as you scale orchestrated, microservice deployments anywhere you need to and for whatever use cases are needed in an agile and innovative way.
endif::iRancher[]

Modernize::
Bring applications and data into modern computing

ifdef::iRancher[]
* FixMe - Using {pn_Rancher} enables you to simplify management and make significant IT savings as you scale orchestrated, microservice deployments anywhere you need to and for whatever use cases are needed in an agile and innovative way.
endif::iRancher[]

Accelerate::
Accelerate business transformation through the power of open source software

ifdef::iRancher[]
* FixMe - Using {pn_Rancher} enables you to simplify management and make significant IT savings as you scale orchestrated, microservice deployments anywhere you need to and for whatever use cases are needed in an agile and innovative way.
endif::iRancher[]

