== Summary

Using components and offerings from {companyName} and the {portfolioName} portfolio streamlines your ability to quickly and effectively engage in a digital transformation, taking advantage of cloud native resources and disciplines. Using such technology approaches lets you deploy and leverage transformations of your infrastructure into a durable, reliable enterprise-grade environment.

Simplify::
Simplify and optimize your existing IT environments

ifeval::["{focus}" == "{an_Rancher}"]
* Using {pn_Rancher} enables you to simplify Kubernetes cluster deployment and management of the the infrastructure components.
endif::[]
ifeval::["{focus}" == "{an_RKE1}"]
* FixMe-Using {pn_RKE1} enables you to simplify Kubernetes cluster deployment and management of the the infrastructure components.
endif::[]
ifeval::["{focus}" == "{an_RKE2}"]
* FixMe-Using {pn_RKE2} enables you to simplify Kubernetes cluster deployment and management of the the infrastructure components.
endif::[]
ifeval::["{focus}" == "{an_K3s}"]
* FixMe-Using {pn_K3s} enables you to simplify Kubernetes cluster deployment and management of the the infrastructure components.
endif::[]

Modernize::
Bring applications and data into modern computing

ifeval::["{focus}" == "{an_Rancher}"]
* With {pn_Rancher}, the digital transformation to containerized applications can benefit from the ability both to manage many target clusters, for each of the respective user bases and to facilitate the actual workload deployments.
endif::[]
ifeval::["{focus}" == "{an_RKE1}"]
* FixMe-With {pn_RKE1}, the digital transformation to containerized applications can benefit from the ability both to manage many target clusters, for each of the respective user bases and to facilitate the actual workload deployments.
endif::[]
ifeval::["{focus}" == "{an_RKE2}"]
* FixMe-With {pn_RKE2}, the digital transformation to containerized applications can benefit from the ability both to manage many target clusters, for each of the respective user bases and to facilitate the actual workload deployments.
endif::[]
ifeval::["{focus}" == "{an_K3s}"]
* FixMe-With {pn_K3s}, the digital transformation to containerized applications can benefit from the ability both to manage many target clusters, for each of the respective user bases and to facilitate the actual workload deployments.
endif::[]

Accelerate::
Accelerate business transformation through the power of open source software

ifeval::["{focus}" == "{an_Rancher}"]
* Given the open source nature of {pn_Rancher} and the underlying software components, you can simplify management and make significant IT savings as you scale orchestrated, microservice deployments anywhere you need to and for whatever use cases are needed in an agile and innovative way.
endif::[]
ifeval::["{focus}" == "{an_RKE1}"]
* FixMe-Given the open source nature of {pn_RKE1} and the underlying software components, you can simplify management and make significant IT savings as you scale orchestrated, microservice deployments anywhere you need to and for whatever use cases are needed in an agile and innovative way.
endif::[]
ifeval::["{focus}" == "{an_RKE2}"]
* FixMe-Given the open source nature of {pn_RKE2} and the underlying software components, you can simplify management and make significant IT savings as you scale orchestrated, microservice deployments anywhere you need to and for whatever use cases are needed in an agile and innovative way.
endif::[]
ifeval::["{focus}" == "{an_K3s}"]
* FixMe-Given the open source nature of {pn_K3s} and the underlying software components, you can simplify management and make significant IT savings as you scale orchestrated, microservice deployments anywhere you need to and for whatever use cases are needed in an agile and innovative way.
endif::[]



